# Практическое занятие: Библиотека NumPy

В этом разделе мы изучим:
- Что такое NumPy и зачем он нужен
- Создание одномерных и двумерных массивов
- Арифметические операции с массивами
- Агрегационные функции
- Индексация и срезы

В конце вас ждут задачи для самостоятельной работы!

## Теоретическая часть

**NumPy** — это библиотека для работы с многомерными массивами и матрицами, а также для выполнения высокоуровневых математических операций над этими структурами данных.

**Основные типы данных в NumPy:**
- **Одномерный массив** (`1D array`): аналог списка в Python.
- **Двумерный массив** (`2D array`): аналог матрицы (строки и столбцы).
- **Многомерные массивы** (`nD array`): массивы с более чем двумя измерениями.

Массивы в NumPy эффективнее списков Python по скорости и памяти.

In [1]:
import numpy as np

# Создание одномерного массива
arr = np.array([1, 2, 3, 4, 5])
print("Одномерный массив:", arr)

Одномерный массив: [1 2 3 4 5]


In [2]:
# Создание двумерного массива (матрицы)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Двумерный массив:\n", matrix)

Двумерный массив:
 [[1 2 3]
 [4 5 6]]


## Арифметические операции в NumPy

### Основные операции с массивами

NumPy предоставляет широкий набор арифметических операций для работы с массивами. Эти операции включают:

1. **Сложение** (`+`): Осуществляется поэлементное сложение двух массивов или массива и скаляра.
2. **Вычитание** (`-`): Происходит поэлементное вычитание одного массива из другого или вычитание скаляра из массива.
3. **Умножение** (`*`): Выполняется поэлементное умножение массивов или умножение массива на скаляр.
4. **Деление** (`/`): Осуществляется поэлементное деление массивов или деление массива на скаляр.
5. **Целочисленное деление** (`//`): Выполняется поэлементное целочисленное деление массивов или массива на скаляр.
6. **Остаток от деления** (`%`): Производится поэлементное вычисление остатка от деления массивов или массива на скаляр.
7. **Возведение в степень** (`**`): Реализуется поэлементное возведение элементов массива в степень или возведение массива в степень скаляра.

### Работа с массивами и скалярами

В NumPy операции между массивами и скалярами выполняются поэлементно. Это означает, что каждый элемент массива будет подвергнут арифметической операции с соответствующим элементом другого массива или с заданным скаляром. 

Кроме того, NumPy поддерживает **broadcasting** — механизм, который позволяет выполнять операции между массивами разной формы, распространяя меньший массив вдоль большего.

### Универсальные функции (ufuncs)

NumPy предоставляет **универсальные функции** (ufuncs), которые реализуют арифметические операции и работают поэлементно. Эти функции оптимизированы для работы с массивами и поддерживают высокую производительность.

К примеру:
- `np.add()` — сложение элементов массива.
- `np.subtract()` — вычитание элементов массива.
- `np.multiply()` — умножение элементов массива.
- `np.divide()` — деление элементов массива.

### Учитывая производительность

Все арифметические операции в NumPy выполняются векторизованно, что означает, что операции выполняются без использования явных циклов, что значительно ускоряет их выполнение по сравнению с традиционными подходами в Python. Это делает NumPy очень эффективным инструментом для работы с большими объемами данных.



In [3]:
# Арифметические операции
print("Массив + 10:", arr + 10)
print("Массив * 2:", arr * 2)

Массив + 10: [11 12 13 14 15]
Массив * 2: [ 2  4  6  8 10]


## Агрегационные функции в NumPy

Агрегационные функции в NumPy позволяют выполнять операции свертки или агрегации данных, таких как вычисление суммы, среднего значения, максимума и других статистических характеристик по массиву. Эти функции выполняются быстро и эффективно благодаря векторизации и внутренним оптимизациям NumPy.

### Основные агрегационные функции

1. **`np.sum()`**: Вычисляет сумму элементов массива по заданной оси или для всего массива. Поддерживает работу с многомерными массивами.
   
2. **`np.prod()`**: Вычисляет произведение элементов массива или по заданной оси.
   
3. **`np.min()`**: Возвращает минимальное значение в массиве или по заданной оси.
   
4. **`np.max()`**: Возвращает максимальное значение в массиве или по заданной оси.
   
5. **`np.argmin()`**: Возвращает индекс минимального значения в массиве.
   
6. **`np.argmax()`**: Возвращает индекс максимального значения в массиве.
   
7. **`np.mean()`**: Вычисляет среднее значение всех элементов массива или по заданной оси.
   
8. **`np.median()`**: Вычисляет медиану массива или по заданной оси.
   
9. **`np.std()`**: Вычисляет стандартное отклонение массива или по заданной оси.
   
10. **`np.var()`**: Вычисляет дисперсию массива или по заданной оси.
   
11. **`np.sum()`**: Вычисляет сумму всех элементов массива, поддерживает работу по осям.

### Дополнительные функции

- **`np.all()`**: Проверяет, выполняется ли условие для всех элементов массива.
- **`np.any()`**: Проверяет, выполняется ли условие хотя бы для одного элемента массива.
- **`np.cumsum()`**: Вычисляет накопительную сумму элементов массива.
- **`np.cumprod()`**: Вычисляет накопительное произведение элементов массива.

### Работа с осями

Многие агрегационные функции поддерживают параметр **axis**, который позволяет вычислять агрегированные значения по конкретной оси многомерного массива. Например, для двумерного массива можно вычислить сумму по строкам (axis=1) или по столбцам (axis=0).

### Производительность

Агрегационные функции NumPy работают очень быстро, благодаря использованию векторизации и внутренней оптимизации. Эти функции существенно быстрее, чем аналогичные операции, выполненные с помощью циклов в Python.



In [4]:
# Агрегационные функции
print("Сумма элементов:", np.sum(arr))
print("Среднее значение:", np.mean(arr))
print("Максимум:", np.max(arr))
print("Минимум:", np.min(arr))

Сумма элементов: 15
Среднее значение: 3.0
Максимум: 5
Минимум: 1


## Индексация и срезы в NumPy

Индексация и срезы в NumPy позволяют эффективно извлекать, изменять или обновлять данные в многомерных массивах. NumPy предоставляет мощные инструменты для работы с данными, аналогичные стандартным возможностям Python для списков, но с дополнительными возможностями и производительностью.

### Основные способы индексации

1. **Индексация с использованием целых чисел**: 
   Каждый элемент массива можно получить по его индексу, начиная с 0 для первого элемента.
   
2. **Индексация с использованием отрицательных чисел**: 
   Отрицательные индексы позволяют обращаться к элементам с конца массива, где -1 — это последний элемент, -2 — предпоследний и так далее.

3. **Индексация с использованием срезов**:
   Срезы позволяют извлекать подмассивы из массива, задавая начальный и конечный индексы. Формат среза: `[start:stop:step]`.

4. **Массивы индексов**:
   Можно использовать другие массивы или списки индексов для извлечения нескольких элементов одновременно, например, извлечь элементы по списку индексов.

### Индексация в многомерных массивах

1. **Индексация по строкам и столбцам**:
   В двумерных массивах можно индексировать строки и столбцы с помощью индексов в формате `[row_index, col_index]`.

2. **Срезы по осям**:
   Срезы также поддерживаются для многомерных массивов, где можно указать диапазоны для каждой оси. Например, `array[:, 1:4]` извлечет все строки, но только столбцы с индексами от 1 до 3.

3. **Сложные срезы**:
   Можно использовать срезы с несколькими диапазонами или условиями. Например, извлечь все элементы определенной строки, удовлетворяющие определенному условию.

### Маскировка и булева индексация

- **Булева индексация** позволяет извлекать элементы массива, которые удовлетворяют определенному условию, создавая логическую маску.
- Массив с булевыми значениями (True/False) может использоваться для индексации, чтобы выбрать только те элементы, которые соответствуют маске.



In [5]:
# Индексация и срезы
print("Первый элемент:", arr[0])
print("Последние три элемента:", arr[-3:])

print("Элемент матрицы [1,2]:", matrix[1,2])

Первый элемент: 1
Последние три элемента: [3 4 5]
Элемент матрицы [1,2]: 6


In [6]:
# Генерация случайных массивов
random_array = np.random.rand(3, 4)
print("Случайный массив 3x4:\n", random_array)

Случайный массив 3x4:
 [[0.17690676 0.74953662 0.6526926  0.65053921]
 [0.08946759 0.33801973 0.48817821 0.24600326]
 [0.80611875 0.71149614 0.43194838 0.22979688]]


In [7]:
# Создание массива из диапазона чисел
range_array = np.arange(0, 20, 2)
print("Массив с шагом 2:", range_array)

Массив с шагом 2: [ 0  2  4  6  8 10 12 14 16 18]


## ✨ Задания для самостоятельной работы

1. Создайте массив из чисел от 10 до 30 и найдите их сумму.
2. Создайте двумерный массив размером 4x4 из случайных чисел и найдите сумму всех элементов.
3. Из двумерного массива выберите все элементы первой строки.
4. Создайте одномерный массив из 15 элементов и найдите максимум, минимум и среднее значение.

In [12]:
array_1 = np.arange(10,31)
print(np.sum(array_2))

777


In [11]:
array_2 = np.random.randint(1, 100, size=(4,4))
print(array_2)

[[50 27 78 70]
 [27 12 56 19]
 [63 91 54 42]
 [ 2 43 63 80]]


In [13]:
print(array_2[0, :])

[50 27 78 70]
